[package]
name = "GRender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.12.1"
glutin = "0.30.7"

# native
# cargo build

# web-sys
# cargo build --target wasm32-unknown-unknown
